// <auto-generated />
using Holtz_PDV.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Holtz_PDV.Migrations
{
    [DbContext(typeof(Holtz_PDVContext))]
    [Migration("20200901092703_Add-CliSts")]
    partial class AddCliSts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Holtz_PDV.Models.Cliente", b =>
                {
                    b.Property<int>("CliCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(8);

                    b.Property<string>("CliCpfCnpj")
                        .HasColumnType("VARCHAR(18)");

                    b.Property<string>("CliEnd")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("CliNomFan")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("CliRaz")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<sbyte>("CliSts")
                        .HasColumnType("TINYINT");

                    b.HasKey("CliCod");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
