// <auto-generated />
using System;
using Holtz_PDV.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Holtz_PDV.Migrations
{
    [DbContext(typeof(Holtz_PDVContext))]
    partial class Holtz_PDVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.Seq_MarCod", "'Seq_MarCod', '', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:.Seq_PedCod", "'Seq_PedCod', '', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:.Seq_ProCod", "'Seq_ProCod', '', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Holtz_PDV.Models.Cidade", b =>
                {
                    b.Property<int>("CidCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CidIBGE")
                        .HasColumnType("int");

                    b.Property<string>("CidNom")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("EstadoEstCod")
                        .HasColumnName("EstCod")
                        .HasColumnType("INT");

                    b.HasKey("CidCod");

                    b.HasIndex("EstadoEstCod");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("Holtz_PDV.Models.Cliente", b =>
                {
                    b.Property<int>("CliCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CidadeCidCod")
                        .HasColumnName("CidCod")
                        .HasColumnType("INT");

                    b.Property<string>("CliBai")
                        .HasColumnType("VARCHAR(130)");

                    b.Property<string>("CliCpfCnpj")
                        .HasColumnType("VARCHAR(18)");

                    b.Property<string>("CliNomFan")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("CliRaz")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("CliRua")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<byte?>("CliSts")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("CliTip")
                        .HasColumnType("TINYINT");

                    b.HasKey("CliCod");

                    b.HasIndex("CidadeCidCod");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Holtz_PDV.Models.Estado", b =>
                {
                    b.Property<int>("EstCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstNom")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("EstUf")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2)");

                    b.HasKey("EstCod");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Holtz_PDV.Models.Marca", b =>
                {
                    b.Property<int>("MarCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValueSql("NEXT VALUE FOR Seq_MarCod");

                    b.Property<string>("MarNom")
                        .HasColumnType("VARCHAR(130)");

                    b.Property<byte?>("MarSts")
                        .HasColumnType("TINYINT");

                    b.HasKey("MarCod");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("Holtz_PDV.Models.Pedido", b =>
                {
                    b.Property<int>("PedCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValueSql("NEXT VALUE FOR Seq_PedCod");

                    b.Property<int?>("PedCliCod")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("PedDtaEms")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("PedDtaFat")
                        .HasColumnType("DATETIME");

                    b.Property<byte?>("PedSts")
                        .HasColumnType("tinyint");

                    b.HasKey("PedCod");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Holtz_PDV.Models.Produto", b =>
                {
                    b.Property<int>("ProCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValueSql("NEXT VALUE FOR Seq_ProCod");

                    b.Property<int?>("MarcaMarCod")
                        .HasColumnName("MarCod")
                        .HasColumnType("INT");

                    b.Property<string>("ProNom")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("ProObs")
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<byte?>("ProSts")
                        .HasColumnType("TINYINT");

                    b.Property<decimal>("ProVlrCus")
                        .HasColumnType("DECIMAL(17,2)");

                    b.Property<decimal>("ProVlrVen")
                        .HasColumnType("DECIMAL(17,2)");

                    b.HasKey("ProCod");

                    b.HasIndex("MarcaMarCod");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Holtz_PDV.Models.Cidade", b =>
                {
                    b.HasOne("Holtz_PDV.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoEstCod")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Holtz_PDV.Models.Cliente", b =>
                {
                    b.HasOne("Holtz_PDV.Models.Cidade", "Cidade")
                        .WithMany("Clientes")
                        .HasForeignKey("CidadeCidCod")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Holtz_PDV.Models.Produto", b =>
                {
                    b.HasOne("Holtz_PDV.Models.Marca", "Marca")
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaMarCod")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
